### ISSUE TITLE
Destroy hides whether a delete occurred.

### ISSUE THREAD

**Issue by gordysc** [mathewdgardner/knex-supermodel#3]
Currently when I destroy a model, I don't have any visibility into whether something was actually deleted.  Any concerns with me changing this logic to return the number of rows affected?

```
destroy(opts = {}) {
    const knex = Util.assertKnex(opts.trx || opts.knex || this._trx || Config.knex);
    const id = opts.id || { id: this.id };

    return knex(Util.table(this))
      .del()
      .where(id)
      .return(this);
  }
```

**Comment by mathewdgardner** [comment]
I wasn't sure what it should return, tbh, so I was lazy. I'm ok with a change but am not sure what it should return other than a boolean. What do you think?

**Comment by mathewdgardner** [comment]
> Any concerns with me changing this logic to return the number of rows affected?

@gordysc I just re-read this. I think that would work for the static destroy but an instance's destroy would only ever return 0 or 1, effectively boolean. What do you think?

**Comment by mathewdgardner** [comment]
@gordysc What do you think about #4?

**Comment by gordysc** [comment]
@mathewdgardner I like it! I can update the PR with this if that works for you?

**Comment by mathewdgardner** [comment]
@gordysc Sure thing
